spring:
  application:
    name: xxl-job-combat-project

xxl:
  job:
    # 调度中心配置
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin # 调度中心地址
    # 执行器配置
    executor:
      appname: ${spring.application.name} # 执行器名称，必须全局唯一，在调度中心配置时使用
      logpath: ./logs/xxl-job/${spring.application.name} # 任务日志存放路径
      logretentiondays: 30 # 日志保留天数
    # 通信令牌
    accessToken: default_token # 必须与调度中心配置的 accessToken 一致
server:
  port: 51001
