server:
  port: 11200


spring:
  rabbitmq:
    host: localhost
    port: 45672
    username: user
    password: 123qwe
    # 需要去 rabbitmq 中自己创建一个虚拟主机
    virtual-host: spring-test
    # 发送方确认模式 simple,correlated,none;
    publisher-confirm-type: correlated
    # 启用发送失败退回模式
    publisher-returns: true


    listener:
      simple:
        # NONE，MANUAL，AUTO
        # manual 为手动确认模式
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        #  预取消息数量，防止一个消费者囤积过多消息
        prefetch: 1

    # --- 连接池和缓存 ---
    cache:
      channel:
        size: 25 # 通道缓存大小，根据并发量调整

